package com.github.libretube.helpers

import android.util.Log
import com.github.libretube.api.obj.Subtitle
import com.github.libretube.helpers.ProxyHelper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonPrimitive
import okhttp3.OkHttpClient
import okhttp3.Request
import java.util.concurrent.TimeUnit

/**
 * Fetches and parses subtitle/caption files to extract plain text transcript
 * with timestamps for AI processing.
 */
object TranscriptHelper {
    private const val TAG = "TranscriptHelper"

    private val httpClient = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    data class TranscriptSegment(
        val startMs: Long,
        val endMs: Long,
        val text: String
    )

    /**
     * Fetches the best available subtitle and parses it into transcript segments.
     * Prefers English, then auto-generated, then any available.
     */
    var lastError: String? = null
        private set

    suspend fun fetchTranscript(subtitles: List<Subtitle>): List<TranscriptSegment>? = withContext(Dispatchers.IO) {
        lastError = null
        Log.i(TAG, "fetchTranscript: subtitles count=${subtitles.size}")
        if (subtitles.isEmpty()) {
            lastError = "No subtitles in streams"
            Log.i(TAG, "fetchTranscript: no subtitles available")
            return@withContext null
        }

        subtitles.forEach { s ->
            Log.i(TAG, "fetchTranscript: subtitle code=${s.code}, autoGen=${s.autoGenerated}, mime=${s.mimeType}, url=${s.url}")
        }

        // Sort: English non-auto first, then English auto, then non-auto any, then any
        val sorted = subtitles.sortedWith(
            compareByDescending<Subtitle> { it.code?.startsWith("en") == true }
                .thenBy { it.autoGenerated == true }
        )

        for (subtitle in sorted) {
            try {
                val rawUrl = subtitle.url
                if (rawUrl.isNullOrBlank()) {
                    lastError = "Subtitle '${subtitle.code}' has null/blank url"
                    Log.i(TAG, "fetchTranscript: $lastError")
                    continue
                }

                // Rewrite URL using proxy preference (same as player does for streams)
                val url = ProxyHelper.rewriteUrlUsingProxyPreference(rawUrl)
                Log.i(TAG, "fetchTranscript: trying '${subtitle.code}' url=$url")

                val request = Request.Builder().url(url).build()
                val response = httpClient.newCall(request).execute()
                Log.i(TAG, "fetchTranscript: HTTP ${response.code} for '${subtitle.code}'")

                if (!response.isSuccessful) {
                    lastError = "HTTP ${response.code} for '${subtitle.code}'"
                    continue
                }

                val content = response.body?.string()
                if (content.isNullOrBlank()) {
                    lastError = "Empty body for '${subtitle.code}'"
                    continue
                }
                Log.i(TAG, "fetchTranscript: content len=${content.length}, first 100=${content.take(100)}")

                val segments = parseSubtitle(content, subtitle.mimeType)
                Log.i(TAG, "fetchTranscript: parsed ${segments.size} segments from '${subtitle.code}'")
                if (segments.isEmpty()) {
                    lastError = "Parsed 0 segments from '${subtitle.code}' (mime=${subtitle.mimeType}, len=${content.length})"
                    continue
                }

                return@withContext segments
            } catch (e: Exception) {
                lastError = "${e.javaClass.simpleName}: ${e.message}"
                Log.i(TAG, "fetchTranscript: exception: $lastError")
                continue
            }
        }

        null
    }

    /**
     * Parses subtitle content (SRT, VTT, or JSON3) into transcript segments.
     */
    private fun parseSubtitle(content: String, mimeType: String?): List<TranscriptSegment> {
        return when {
            mimeType?.contains("json3") == true || content.trimStart().startsWith("{") -> parseJson3(content)
            mimeType?.contains("ttml") == true || content.contains("<tt ") || content.contains("<tt>") -> parseTtml(content)
            content.contains("WEBVTT") -> parseVtt(content)
            else -> parseSrt(content)
        }
    }

    private fun parseTtml(content: String): List<TranscriptSegment> {
        val segments = mutableListOf<TranscriptSegment>()
        try {
            // Match <p begin="..." end="...">text</p> or <p begin="..." dur="...">text</p>
            val pPattern = Regex("<p[^>]*\\sbegin=\"([^\"]+)\"[^>]*(?:\\send=\"([^\"]+)\"|\\sdur=\"([^\"]+)\")?[^>]*>(.*?)</p>", setOf(RegexOption.DOT_MATCHES_ALL))
            
            for (match in pPattern.findAll(content)) {
                val begin = match.groupValues[1]
                val end = match.groupValues[2].ifBlank { match.groupValues[3] }
                val rawText = match.groupValues[4]
                
                val startMs = parseTtmlTime(begin)
                val endMs = if (end.isNotBlank()) parseTtmlTime(end) else startMs
                
                val text = cleanText(rawText)
                if (text.isNotBlank()) {
                    segments.add(TranscriptSegment(startMs, endMs, text))
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to parse TTML: ${e.message}")
        }
        return segments
    }

    private fun parseTtmlTime(time: String): Long {
        // TTML time formats: HH:MM:SS.mmm, HH:MM:SS:mmm, or seconds with 's' suffix
        return try {
            if (time.endsWith("s")) {
                (time.removeSuffix("s").toDouble() * 1000).toLong()
            } else {
                val parts = time.replace(",", ".").split(":")
                when (parts.size) {
                    3 -> {
                        val h = parts[0].toLong()
                        val m = parts[1].toLong()
                        val s = parts[2].toDouble()
                        ((h * 3600 + m * 60) * 1000 + (s * 1000).toLong())
                    }
                    4 -> {
                        val h = parts[0].toLong()
                        val m = parts[1].toLong()
                        val s = parts[2].toLong()
                        val ms = parts[3].toLong()
                        (h * 3600 + m * 60 + s) * 1000 + ms
                    }
                    else -> 0L
                }
            }
        } catch (e: Exception) {
            0L
        }
    }

    private fun parseSrt(content: String): List<TranscriptSegment> {
        val segments = mutableListOf<TranscriptSegment>()
        val blocks = content.split("\n\n").filter { it.isNotBlank() }

        for (block in blocks) {
            val lines = block.trim().lines()
            if (lines.size < 2) continue

            // Skip the index line (number) if present
            val timeLineIndex = if (lines[0].toIntOrNull() != null) 1 else 0
            if (lines.size <= timeLineIndex) continue

            val timeLine = lines[timeLineIndex]
            val timeMatch = Regex("(\\d{2}):(\\d{2}):(\\d{2})[,.](\\d{3})\\s*-->\\s*(\\d{2}):(\\d{2}):(\\d{2})[,.](\\d{3})")
                .find(timeLine) ?: continue

            val startMs = timeToMs(
                timeMatch.groupValues[1], timeMatch.groupValues[2],
                timeMatch.groupValues[3], timeMatch.groupValues[4]
            )
            val endMs = timeToMs(
                timeMatch.groupValues[5], timeMatch.groupValues[6],
                timeMatch.groupValues[7], timeMatch.groupValues[8]
            )

            val text = lines.drop(timeLineIndex + 1).joinToString(" ").trim()
            if (text.isNotBlank()) {
                segments.add(TranscriptSegment(startMs, endMs, cleanText(text)))
            }
        }

        return segments
    }

    private fun parseVtt(content: String): List<TranscriptSegment> {
        val segments = mutableListOf<TranscriptSegment>()
        val blocks = content.split("\n\n").filter { it.isNotBlank() }

        for (block in blocks) {
            val lines = block.trim().lines()
            if (lines.isEmpty()) continue

            val timeLine = lines.firstOrNull { it.contains("-->") } ?: continue
            val timeMatch = Regex("(\\d{2}):(\\d{2}):(\\d{2})[,.](\\d{3})\\s*-->\\s*(\\d{2}):(\\d{2}):(\\d{2})[,.](\\d{3})")
                .find(timeLine) ?: continue

            val startMs = timeToMs(
                timeMatch.groupValues[1], timeMatch.groupValues[2],
                timeMatch.groupValues[3], timeMatch.groupValues[4]
            )
            val endMs = timeToMs(
                timeMatch.groupValues[5], timeMatch.groupValues[6],
                timeMatch.groupValues[7], timeMatch.groupValues[8]
            )

            val text = lines.drop(1).filter { !it.contains("-->") }.joinToString(" ").trim()
            if (text.isNotBlank()) {
                segments.add(TranscriptSegment(startMs, endMs, cleanText(text)))
            }
        }

        return segments
    }

    private fun parseJson3(content: String): List<TranscriptSegment> {
        val segments = mutableListOf<TranscriptSegment>()
        try {
            val json = kotlinx.serialization.json.Json { ignoreUnknownKeys = true }
            val root = json.parseToJsonElement(content).jsonObject
            val events = root["events"]?.jsonArray ?: return segments

            for (event in events) {
                val obj = event.jsonObject
                val startMs = obj["tStartMs"]?.jsonPrimitive?.content?.toLongOrNull() ?: continue
                val endMs = obj["dDurationMs"]?.jsonPrimitive?.content?.toLongOrNull()?.let { startMs + it } ?: startMs
                val segs = obj["segs"]?.jsonArray ?: continue

                val text = segs.mapNotNull { seg ->
                    seg.jsonObject["utf8"]?.jsonPrimitive?.content
                }.joinToString("").trim()

                if (text.isNotBlank()) {
                    segments.add(TranscriptSegment(startMs, endMs, cleanText(text)))
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to parse JSON3: ${e.message}")
        }

        return segments
    }

    private fun timeToMs(h: String, m: String, s: String, ms: String): Long {
        return (h.toLong() * 3600 + m.toLong() * 60 + s.toLong()) * 1000 + ms.toLong()
    }

    private fun cleanText(text: String): String {
        return text
            .replace("<[^>]*>".toRegex(), "") // remove HTML tags
            .replace("&amp;", "&")
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&nbsp;", " ")
            .replace("\\{.*?\\}".toRegex(), "") // remove VTT styling cues
            .trim()
    }

    /**
     * Converts transcript segments into a text string with timestamps for AI context.
     * Format: [MM:SS] text
     */
    fun segmentsToText(segments: List<TranscriptSegment>): String {
        return segments.joinToString("\n") { seg ->
            val mins = seg.startMs / 60000
            val secs = (seg.startMs % 60000) / 1000
            "[%02d:%02d] %s".format(mins, secs, seg.text)
        }
    }

    /**
     * Truncates transcript to fit within token budget (rough estimate: ~4 chars per token).
     */
    fun truncateForContext(segments: List<TranscriptSegment>, maxChars: Int = 24000): String {
        val fullText = segmentsToText(segments)
        if (fullText.length <= maxChars) return fullText

        // Keep the first portion and add a note
        return fullText.take(maxChars) + "\n[... transcript truncated ...]"
    }
}
